# Generated by Django 5.2.16 on 2026-07-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional direct URL to a product image.'),
        ),
    ]
