# Generated by Django 5.2.16 on 2026-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Optional direct URL to a product image.', max_length=255),
        ),
    ]
